version: '3.8'

services:
  school-db:
    image: postgres:latest
    container_name: school-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ilker
      POSTGRES_DB: SchoolDB
    volumes:
      - C:\postgres_datapart:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

  spring-app:
    build: .
    container_name: spring-app
    depends_on:
      - school-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://school-db:5432/SchoolDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ilker
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: